/* LIVE SERVICE - TMA realtime dari sdatelemetry.com/fmsciawi (khusus inlet & outlet Bendungan Ciawi) */
const LIVE_SOURCE="https://sdatelemetry.com/fmsciawi/";
const LIVE_PROXIES=["https://api.allorigins.win/raw?url=","https://api.codetabs.com/v1/proxy?quest=","https://corsproxy.io/?url="];
const LIVE_TARGETS=["INLET BENDUNGAN CIAWI","OUTLET BENDUNGAN CIAWI"];
let liveTimer=null;let liveLastTs=null;
function liveNorm(s){return (s||"").replace(/\s+/g," ").trim().toUpperCase();}
async function fetchWithTimeout(url,ms){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal});if(!r.ok)throw new Error("HTTP "+r.status);return await r.text();}finally{clearTimeout(t);}}
async function fetchLiveHtml(){for(let i=0;i<LIVE_PROXIES.length;i++){try{return await fetchWithTimeout(LIVE_PROXIES[i]+encodeURIComponent(LIVE_SOURCE),12000);}catch(e){console.warn("Proxy gagal: "+LIVE_PROXIES[i]);}}throw new Error("Semua proxy gagal");}
function parseLiveTable(html){const doc=new DOMParser().parseFromString(html,"text/html");const out={};doc.querySelectorAll("tr").forEach(tr=>{const cells=Array.from(tr.querySelectorAll("td,th"));const idx=cells.findIndex(c=>{const t=liveNorm(c.textContent);return LIVE_TARGETS.some(x=>t===x||t.indexOf(x)===0);});if(idx===-1)return;const name=liveNorm(cells[idx].textContent);const target=LIVE_TARGETS.find(x=>name===x||name.indexOf(x)===0);if(!target)return;out[target]={jam:cells[idx+1]?liveNorm(cells[idx+1].textContent):"",tma:cells[idx+2]?liveNorm(cells[idx+2].textContent):"",debit:cells[idx+3]?liveNorm(cells[idx+3].textContent):""};});return out;}
function setLiveBadge(mode){const b=document.getElementById("live-badge");if(!b)return;if(mode==="live"){b.textContent="LIVE";b.className="text-[10px] px-2 py-0.5 rounded bg-siaga-normal/15 text-siaga-normal border border-siaga-normal/40 font-bold";}else if(mode==="offline"){b.textContent="OFFLINE";b.className="text-[10px] px-2 py-0.5 rounded bg-siaga-2/15 text-siaga-2 border border-siaga-2/40 font-bold";}else{b.textContent="MENYAMBUNG";b.className="text-[10px] px-2 py-0.5 rounded bg-surface-container text-on-surface-variant font-bold";}}
function renderLive(data){const map={"INLET BENDUNGAN CIAWI":"inlet","OUTLET BENDUNGAN CIAWI":"outlet"};let found=0;LIVE_TARGETS.forEach(t=>{const k=map[t];const d=data[t];if(!d)return;found++;const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v;};set("live-"+k+"-jam",d.jam||"--:--");set("live-"+k+"-tma",(d.tma===""?"—":d.tma)+" m");set("live-"+k+"-debit",(d.debit===""?"—":d.debit)+" m³/s");});const now=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Jakarta",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date());const u=document.getElementById("live-update-time");if(u)u.textContent=now+" WIB";setLiveBadge(found===LIVE_TARGETS.length?"live":"offline");return found;}
async function refreshLiveNow(){setLiveBadge("loading");try{const html=await fetchLiveHtml();const data=parseLiveTable(html);if(!data||Object.keys(data).length===0)throw new Error("Tabel tidak ditemukan");const tIn=parseFloat((data["INLET BENDUNGAN CIAWI"]||{}).tma);const tOut=parseFloat((data["OUTLET BENDUNGAN CIAWI"]||{}).tma);if(!isNaN(tIn)&&!isNaN(tOut)&&typeof computeLiveNeraca==="function"){const now=Date.now();const dt=liveLastTs?((now-liveLastTs)/1000):0;liveLastTs=now;renderLiveNeraca(computeLiveNeraca(tIn,tOut,dt));}renderLive(data);}catch(e){console.warn("Live telemetry offline: "+e.message);setLiveBadge("offline");}}
function startLivePolling(ms){refreshLiveNow();if(liveTimer)clearInterval(liveTimer);liveTimer=setInterval(refreshLiveNow,ms||60000);}
document.addEventListener("DOMContentLoaded",function(){startLivePolling(60000);});
