/* POWER GATE v2 - sequenza avvi futuristik */
(function(){var RM=window.matchMedia&&matchMedia("(prefers-reduced-motion: reduce)").matches;var st=document.createElement("style");
st.textContent="#power-gate{position:fixed;inset:0;z-index:99999;background:radial-gradient(1200px 700px at 50% 42%,#0a1424 0%,#04070d 60%,#020409 100%);display:flex;align-items:center;justify-content:center;user-select:none;overflow:hidden;font-family:'JetBrains Mono',monospace}";
st.textContent+="#power-gate .pg-grid{position:absolute;inset:0;background-image:linear-gradient(rgba(76,215,246,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(76,215,246,.05) 1px,transparent 1px);background-size:44px 44px;animation:pgGrid 9s linear infinite}";
st.textContent+="#power-gate .pg-vig{position:absolute;inset:0;background:radial-gradient(closest-side,transparent 55%,rgba(0,0,0,.55) 100%)}";
st.textContent+="#power-gate .pg-glow{position:absolute;left:50%;top:40%;width:560px;height:560px;transform:translate(-50%,-50%) scale(.35);opacity:0;border-radius:50%;background:radial-gradient(circle,rgba(255,209,102,.26) 0%,rgba(255,209,102,.08) 42%,transparent 70%);transition:transform 2.4s cubic-bezier(.16,.84,.3,1),opacity 1.6s ease}";
st.textContent+="#power-gate.on .pg-glow{transform:translate(-50%,-50%) scale(1);opacity:1}#power-gate .pg-scan{position:absolute;left:0;right:0;top:-12%;height:14%;background:linear-gradient(180deg,transparent,rgba(76,215,246,.12),rgba(76,215,246,.3),rgba(76,215,246,.12),transparent);opacity:0}";
st.textContent+="#power-gate.on .pg-scan{animation:pgScan 2.8s cubic-bezier(.3,.6,.4,1) .5s 1 forwards}#power-gate .pg-core{position:relative;display:flex;flex-direction:column;align-items:center;gap:12px;padding:32px 46px;border:1px solid rgba(76,215,246,.22);border-radius:14px;background:rgba(6,12,22,.55);backdrop-filter:blur(6px)}";
st.textContent+="#power-gate .pg-corner{position:absolute;width:18px;height:18px;border-color:#4cd7f6;border-style:solid;border-width:0}#power-gate .c1{top:-2px;left:-2px;border-top-width:2px;border-left-width:2px}#power-gate .c2{top:-2px;right:-2px;border-top-width:2px;border-right-width:2px}";
st.textContent+="#power-gate .c3{bottom:-2px;left:-2px;border-bottom-width:2px;border-left-width:2px}#power-gate .c4{bottom:-2px;right:-2px;border-bottom-width:2px;border-right-width:2px}#power-gate .pg-title{color:#7dd3fc;font-size:13px;letter-spacing:.28em;font-weight:700}";
st.textContent+="#power-gate .pg-sub{color:#64748b;font-size:10px;letter-spacing:.18em}#power-gate .pg-lever{position:relative;width:74px;height:118px;border:1px solid rgba(148,163,184,.35);border-radius:10px;background:linear-gradient(180deg,#0d1626,#0a111d);cursor:grab;margin:4px 0}";
st.textContent+="#power-gate .pg-lever .slot{position:absolute;left:50%;top:12px;bottom:12px;width:8px;transform:translateX(-50%);border-radius:4px;background:#050a12;box-shadow:inset 0 0 8px #000}";
st.textContent+="#power-gate .pg-lever .arm{position:absolute;left:50%;top:16px;width:10px;height:50px;transform:translateX(-50%);transform-origin:50% 10%;border-radius:5px;background:linear-gradient(180deg,#e2e8f0,#94a3b8);transition:transform 1.1s cubic-bezier(.2,.9,.25,1)}";
st.textContent+="#power-gate .pg-lever .knob{position:absolute;left:50%;top:-12px;width:26px;height:26px;transform:translateX(-50%);border-radius:50%;background:radial-gradient(circle at 35% 30%,#f87171,#b91c1c 70%);box-shadow:0 0 14px rgba(248,113,113,.5)}#power-gate.on .pg-lever .arm{transform:translateX(-50%) rotate(176deg)}";
st.textContent+="#power-gate .pg-hint{color:#64748b;font-size:10px;letter-spacing:.2em;animation:pgBlink 1.8s infinite}#power-gate .pg-log{width:300px;min-height:92px;font-size:10px;line-height:1.7;color:#35e0a1;text-align:left}";
st.textContent+="#power-gate .pg-log .ln{opacity:0;transform:translateY(4px);animation:pgLine .5s ease forwards}#power-gate .pg-bar{width:300px;height:3px;background:#0b1524;border-radius:2px;overflow:hidden}#power-gate .pg-bar i{display:block;height:100%;width:0;background:linear-gradient(90deg,#4cd7f6,#35e0a1);transition:width 2.6s cubic-bezier(.2,.8,.3,1)}";
st.textContent+="#power-gate .pg-pct{color:#94a3b8;font-size:10px;letter-spacing:.14em}#power-gate.leaving{animation:pgOut 1.1s ease-in-out forwards}@keyframes pgGrid{0%{background-position:0 0}100%{background-position:0 44px}}@keyframes pgBlink{0%,100%{opacity:.3}50%{opacity:1}}";
st.textContent+="@keyframes pgScan{0%{top:-12%;opacity:0}12%{opacity:1}100%{top:108%;opacity:0}}@keyframes pgLine{to{opacity:1;transform:none}}@keyframes pgOut{0%{opacity:1}55%{opacity:.85;filter:brightness(1.25)}100%{opacity:0;filter:brightness(1.6);transform:scale(1.04)}}";document.head.appendChild(st);
var g=document.createElement("div");g.id="power-gate";g.setAttribute("role","button");g.tabIndex=0;
var H="<div class='pg-grid'></div><div class='pg-glow'></div><div class='pg-vig'></div><div class='pg-scan'></div><div class='pg-core'><span class='pg-corner c1'></span><span class='pg-corner c2'></span><span class='pg-corner c3'></span><span class='pg-corner c4'></span>";
H+="<div class='pg-title'>RUANG KONTROL BENDUNGAN CIAWI</div><div class='pg-sub'>MAIN POWER • SCADA HIDROLOGI</div><div class='pg-lever'><div class='slot'></div><div class='arm'><div class='knob'></div></div></div>";
H+="<div class='pg-hint' id='pg-hint'>TARIK TUAS UNTUK MENGAKTIFKAN</div><div class='pg-log' id='pg-log'></div><div class='pg-bar'><i id='pg-fill'></i></div><div class='pg-pct' id='pg-pct'>DAYA 0%</div></div>";
g.innerHTML=H;
document.body.insertBefore(g,document.body.firstChild);var done=false;
function sfx(){try{var c=new (window.AudioContext||window.webkitAudioContext)();var o=c.createOscillator(),q=c.createGain();o.type="square";o.frequency.value=210;q.gain.setValueAtTime(.12,c.currentTime);q.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.09);o.connect(q);q.connect(c.destination);o.start();o.stop(c.currentTime+.1);
var o2=c.createOscillator(),q2=c.createGain();o2.type="sine";o2.frequency.setValueAtTime(48,c.currentTime+.12);o2.frequency.linearRampToValueAtTime(118,c.currentTime+1.5);q2.gain.setValueAtTime(.0001,c.currentTime+.12);
q2.gain.exponentialRampToValueAtTime(.06,c.currentTime+.5);q2.gain.exponentialRampToValueAtTime(.0001,c.currentTime+2.2);o2.connect(q2);q2.connect(c.destination);o2.start(c.currentTime+.12);o2.stop(c.currentTime+2.3);}catch(e){}}
var LOGS=["> INIT BUS SENSOR TMA ........ OK","> HANDSHAKE TELEMETRI SDA .... OK","> KALIBRASI KONDUIT n=0.015 .. OK","> MUAT NERACA RIIL ........... OK","> SINKRON JAM WIB ............ OK"];
function boot(){if(done)return;done=true;g.classList.add("on");document.getElementById("pg-hint").textContent="SEQUENCE AVVI ATTIVO";sfx();
LOGS.forEach(function(s,i){setTimeout(function(){var d=document.createElement("div");d.className="ln";d.textContent=s;document.getElementById("pg-log").appendChild(d);},600+i*420);});
setTimeout(function(){document.getElementById("pg-fill").style.width="100%";},500);var p=0;var iv=setInterval(function(){p=Math.min(100,p+1);document.getElementById("pg-pct").textContent="DAYA "+p+"%";if(p>=100)clearInterval(iv);},26);
setTimeout(function(){g.classList.add("leaving");},3300);setTimeout(function(){g.remove();document.body.classList.add("booted");},4400);}
function fast(){if(done)return;done=true;g.remove();document.body.classList.add("booted");}
if(RM){g.addEventListener("click",fast);}else{g.addEventListener("click",boot);}
g.addEventListener("keydown",function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();if(RM){fast();}else{boot();}}});
})();
