/* SAFETY NET - backup/pulihkan rekaman, favicon+judul+versi, perangkap error ber-log */
const APP_VERSION="v2.23";window.__errLog=[];
function safetyDownload(name,text){const b=new Blob([text],{type:"application/json"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(u);a.remove();},400);}
function safetyPanel(){let p=document.getElementById("safety-panel");if(p)return p;p=document.createElement("div");p.id="safety-panel";p.style.cssText="position:fixed;left:12px;bottom:12px;z-index:9998;display:flex;gap:6px;";
p.innerHTML="<button id='sf-backup'>💾 BACKUP</button><button id='sf-restore'>♻ PULIHKAN</button><button id='sf-errlog'>🧾 LOG ERROR</button>";p.querySelectorAll("button").forEach(function(b){b.style.cssText="background:rgba(11,19,38,.9);border:1px solid rgba(76,215,246,.4);color:#e6edf7;border-radius:6px;padding:4px 8px;font-size:10px;font-weight:700;cursor:pointer;";});document.body.appendChild(p);return p;}
function safetyBackup(){const o={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k.indexOf("ciawi")===0)o[k]=localStorage.getItem(k);}const n=Object.keys(o).length;safetyDownload("ciawi-backup-"+new Date().toISOString().slice(0,16).replace(/[:T]/g,"")+".json",JSON.stringify(o,null,1));toast("Backup sukses: "+n+" kunci rekaman tersimpan ke file","success");}
function safetyRestorePick(){let inp=document.getElementById("sf-file");if(!inp){inp=document.createElement("input");inp.type="file";inp.id="sf-file";inp.accept=".json,application/json";inp.style.display="none";document.body.appendChild(inp);
inp.onchange=function(){const f=inp.files[0];if(!f)return;const r=new FileReader();r.onload=function(){try{const o=JSON.parse(r.result);let n=0;for(const k in o){if(k.indexOf("ciawi")===0){localStorage.setItem(k,o[k]);n++;}}toast("Pulihkan sukses: "+n+" kunci dimuat - reload otomatis","success");setTimeout(function(){location.reload();},1500);}catch(e){toast("File backup tidak valid","error");}};r.readAsText(f);};}inp.click();}
function safetyErrLog(){let L=window.__errLog;try{const s=localStorage.getItem("ciawi-errlog");if(s&&s!=="null"){const P=JSON.parse(s);if(P&&P.length)L=P;}}catch(e){}if(!L||!L.length){toast("Log error kosong - belum ada error tertangkap","info");return;}safetyDownload("ciawi-errlog-"+new Date().toISOString().slice(0,16).replace(/[:T]/g,"")+".json",JSON.stringify(L,null,1));toast("Log error diekspor: "+L.length+" entri","success");}
window.addEventListener("error",function(e){try{window.__errLog.push({t:new Date().toISOString(),msg:String(e.message),src:String(e.filename||""),line:e.lineno||0});if(window.__errLog.length>200)window.__errLog.shift();localStorage.setItem("ciawi-errlog",JSON.stringify(window.__errLog));if(!window.__errToasted){window.__errToasted=true;toast("Error tertangkap - simpan lewat LOG ERROR","warn");}}catch(x){}});
const FAVICON="data:image/svg+xml,<svg%20xmlns=%27http://www.w3.org/2000/svg%27%20viewBox=%270%200%2064%2064%27><rect%20width=%2764%27%20height=%2764%27%20rx=%2712%27%20fill=%27%230b1326%27/><path%20d=%27M10%2038q11-12%2022%200t22%200%27%20stroke=%27%234cd7f6%27%20stroke-width=%277%27%20fill=%27none%27/><path%20d=%27M10%2050q11-10%2022%200t22%200%27%20stroke=%27%2335e0a1%27%20stroke-width=%276%27%20fill=%27none%27/></svg>";
document.head.insertAdjacentHTML("afterbegin","<link rel='icon' href='"+FAVICON+"'>");document.title="Bendungan Ciawi • SCADA Ruang Kontrol • "+APP_VERSION;
document.addEventListener("DOMContentLoaded",function(){safetyPanel();document.getElementById("sf-backup").onclick=safetyBackup;document.getElementById("sf-restore").onclick=safetyRestorePick;document.getElementById("sf-errlog").onclick=safetyErrLog;
const f=document.createElement("footer");f.style.cssText="text-align:center;font-size:10px;color:#64748b;padding:10px 0 14px;letter-spacing:.08em;";f.textContent="BENDUNGAN CIAWI - SCADA RUANG KONTROL • "+APP_VERSION+" • data riil NERACA + telemetri live";document.body.appendChild(f);});
